declare module '*.css';
declare module '*.less';
declare module '*.md';
// declare module 'klein';
declare module '@ant-design/css-animation/*';
declare module 'raf';
declare module 'scroll-into-view-if-needed';
declare module '*.gif';
declare module '*.png';
declare module '*.svg';
